createorders/urls.py
from django.urls import path
from .views import create_order

app_name = "createorders"

urlpatterns = [
    path('create_order/', create_order, name="create_order"),
]

healthApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("register.urls", namespace="register")),
    path("", include("createorders.urls", namespace="createorders")),
]

register/urls.py
from django.urls import path
from .views import home_view,register

app_name = "register"

urlpatterns = [
    path('', home_view, name="home"),
    path('register_patient/', register, name="register_patient"),

]

createorders/models.py
from django.db import models

from register.models import Patient

# Create your models here.
# model to represent patient for registering
class Order(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    medicine = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.patient

register/models.py
from django.db import models

# Create your models here.
# model to represent patient for registering
class Patient(models.Model):
    name = models.CharField(max_length=255,unique=True, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

createorders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

register/forms.py
from django import forms
from .models import Patient

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'

createorders/views.py
from django.shortcuts import render, reverse
from django.http.response import HttpResponseRedirect
from createorders.forms import OrderForm

# Create your views here.
def create_order(request):
    '''Create an order for a patient'''
    form = OrderForm(request.POST or None)
    if form.is_valid():
        form.save() 
        return HttpResponseRedirect(reverse("register:home"))# redirecting to a url
    return render(request, "create_orders.html", {"form":form})

register/views.py
from django.shortcuts import render, reverse
from django.http.response import HttpResponseRedirect
from createorders.models import Order
from register.forms import PatientForm
from register.models import Patient

# Create your views here.

def home_view(request):
    '''Landing page + list view for the orders and corresponding patients'''
    order = Order.objects.all()
    return render(request, "home.html", {"orders": order})

def register(request):
    '''create patient wiht name and address in the model database for patient'''
    form = PatientForm(request.POST or None)
    if form.is_valid():
        form.save() 
        return HttpResponseRedirect(reverse("register:home"))# redirecting to a url
    return render(request, "register.html", {"form":form})

createorders/templates/create_orders.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
    Patient Not Registered???
    <a href="{% url 'register:register_patient' %}" type="button" class="btn btn-primary" >Registration </a>
</div>

    <form method="POST" >
    {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm"/>
    </form>
{% endblock content %}

register/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="d-grid gap-2 col-2 mx-auto">
    <a href="{% url 'register:register_patient' %}" type="button" class="btn btn-primary" >Registration </a>
    <a href="{% url 'createorders:create_order' %}" type="button" class="btn btn-primary">Create Orders</a>
</div>
<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Name</th>
      <th scope="col">Medicine</th>
    </tr>
  </thead>
    <tbody>

    {% for p in orders %}
        <tr>
        <td scope="col">{{forloop.counter}}</td>
        <td scope="col">{{p.patient}}</td>
        <td scope="col">{{p.medicine}}</td>      
    </tr> 
    {% endfor %}
    </tbody>
  </tbody>
</table>
{% endblock content %}

register/templates/register.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
{% csrf_token %}
{% comment %} <div class="d-grid gap-2 col-2 mx-auto">
    <label class="form-label">Name </label>
    <input type="text" class="form-control-sm" name="name">
    <label class="form-label">Address </label>
    <input type="text" class="form-control-sm" name="name">
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
</div> {% endcomment %}

    {{form.as_p}}
    <input type="submit" value="Submit"/>

</form>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Health APP</title>
  </head>
    <body>
        <div class="container">
        <h1 class="text-center">Health App</h1>
        {% block content %}{% endblock content %}
        </div>
    </body>
</html>